version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: erp
      MYSQL_USER: erp-user
      MYSQL_PASSWORD: erp-password
    ports:
      - 33306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: